version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./minter-test
    environment:
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    ports:
      - 3003:3003
    image: minter:0.3.0
    volumes:
      - node-ipc:/ipc
      - node-bin:/cardano/bin
      - node-nix:/nix
    tty: true
    stdin_open: true

  cardano-node:
    image: inputoutput/cardano-node:1.35.2
    environment:
      - NETWORK=${NETWORK:-testnet}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
      - node-bin:/usr/local/bin
      - node-nix:/nix
    restart: on-failure
    healthcheck:
      # Ping the EKG port to see if it responds.
      # Assuming if EKG isn't up then the rest of cardano-node isn't either.
      test: ["CMD-SHELL", "curl -f 127.0.0.1:12788 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  node-ipc:
  node-bin:
  node-nix:
